import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "ar" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const arabicTranslations: Record<string, string> = {
  // Navigation / Sidebar
  "Dashboard": "لوحة التحكم",
  "Doctors List": "قائمة الأطباء",
  "Patients List": "قائمة المرضى",
  "Manage Bookings": "إدارة الحجوزات",
  "My Profile": "ملفي الشخصي",
  "Messages": "الرسائل",
  "Support & Help": "الدعم والمساعدة",
  "Health Overview": "نظرة عامة على الصحة",
  "Book Appointment": "حجز موعد",
  "My Medications": "أدويتي",
  "Health Quiz & AI": "اختبار الصحة والذكاء الاصطناعي",
  "3D Organ Anatomy": "تشريح الأعضاء ثلاثي الأبعاد",
  "My Patients": "مرضاي",
  "Working Hours": "ساعات العمل",
  "Verification Documents": "وثائق التحقق",
  "Logout": "تسجيل الخروج",
  "Light Mode": "الوضع المضيء",
  "Dark Mode": "الوضع المظلم",
  
  // DashboardLayout / Header
  "Welcome back": "مرحباً بك مجدداً",
  "Smart Clinic Interactive Medical Management Suite": "مجموعة إدارة العيادة الذكية الطبية التفاعلية",
  "Notifications": "الإشعارات",
  "Mark all read": "تحديد الكل كمقروء",
  "No new notifications": "لا توجد إشعارات جديدة",
  "Successfully logged out": "تم تسجيل الخروج بنجاح",
  "Welcome back, ": "مرحباً بك مجدداً، ",
  
  // Profile Page
  "Account Settings": "إعدادات الحساب",
  "Manage your credentials, bio, and visual avatar": "إدارة بيانات الاعتماد والسيرة الذاتية والصورة الشخصية",
  "Profile Photo": "صورة الملف الشخصي",
  "Click the image to upload a new JPG, PNG, or WEBP file.": "اضغط على الصورة لرفع ملف JPG أو PNG أو WEBP جديد.",
  "Display Name": "الاسم المعروض",
  "Email Address": "البريد الإلكتروني",
  "Change Password (Leave blank to keep current)": "تغيير كلمة المرور (اتركها فارغة للاحتفاظ بالحالية)",
  "Enter new password": "أدخل كلمة المرور الجديدة",
  "Save Changes": "حفظ التغييرات",
  "Doctor Public Information": "معلومات الطبيب العامة",
  "Specialty": "التخصص",
  "Verification Status": "حالة التحقق",
  "Consultation Fee": "رسوم الاستشارة",
  "Account State": "حالة الحساب",
  "Verified": "تم التحقق",
  "Pending Verification": "قيد الانتظار",
  "Active": "نشط",
  "Frozen": "مجمد",
  "New file selected": "تم اختيار ملف جديد",
  "Profile updated successfully!": "تم تحديث الملف الشخصي بنجاح!",
  "Failed to update profile.": "فشل تحديث الملف الشخصي.",
  
  // Chat Page
  "Communication & Support Center": "مركز التواصل والدعم الفني",
  "Clinician & Patient Threads": "محادثات الأطباء والمرضى",
  "Search conversations or start new...": "البحث عن محادثات أو بدء جديدة...",
  "Search messages...": "البحث في الرسائل...",
  "Search doctors or patients...": "البحث عن أطباء أو مرضى...",
  "Clinical Monitoring": "مراقبة العيادات",
  "Clinical Conversations": "المحادثات الطبية",
  "Support Chats": "الدعم الفني",
  "Support & Complaints": "الدعم والشكاوى",
  "Active Conversations": "المحادثات النشطة",
  "Start a New Conversation": "بدء محادثة جديدة",
  "Support Channel": "قناة الدعم الفني",
  "Clinical Monitoring (Read Only)": "مراقبة العيادة (قراءة فقط)",
  "Filter messages...": "تصفية الرسائل...",
  "Type message here...": "اكتب رسالة هنا...",
  "Select a user thread from the index sidebar to establish communication": "اختر محادثة من القائمة الجانبية لبدء التواصل",
  "This clinical conversation is monitored (read-only) and cannot be modified or sent messages in.": "هذه المحادثة الطبية تحت المراقبة (وضع القراءة فقط) ولا يمكن التعديل عليها أو إرسال رسائل بها.",
  "Support": "الدعم",
  "Direct Messages": "الرسائل المباشرة",
  "You": "أنت",
  "System Admin": "مسؤول النظام",
  "Online": "متصل",
  "Offline": "غير متصل",
  "Write a message...": "اكتب رسالة...",
  "typing...": "يكتب الآن...",
  "Send": "إرسال",
  "Select a chat to start messaging": "اختر محادثة لبدء المراسلة",
  "Chat Session": "جلسة المحادثة",
  "Start chat": "بدء المحادثة",
  "Messages & Help": "الرسائل والمساعدة",
  "Active Chat": "المحادثة النشطة",
  "No messages yet. Send a message to start the conversation!": "لا توجد رسائل بعد. أرسل رسالة لبدء المحادثة!",
  
  // Role Translations
  "Patient": "مريض",
  "Doctor": "طبيب",
  "Admin": "مسؤول",
  
  // AI Diagnostic / Chatbot Page
  "AI Diagnostic Center": "مركز التشخيص الذكي",
  "Self-assess health severity or converse with our AI medical assistant": "التقييم الذاتي لشدة الأعراض الصحية أو التحدث مع المساعد الطبي الذكي",
  "AI Health Assessment Quiz": "اختبار تقييم الصحة الذكي",
  "AI Medical Chatbot": "روبوت الدردشة الطبي الذكي",
  "Diagnostic Self-Assessment": "التقييم الذاتي للتشخيص",
  "Important Medical Notice": "ملاحظة طبية هامة",
  "These self-assessment quizzes are generated by algorithmic automation. They represent diagnostic guidance metrics, not absolute clinical prescriptions. Always coordinate care with a verified clinical physician.": "يتم إنشاء اختبارات التقييم الذاتي هذه بواسطة الأتمتة الخوارزمية. إنها تمثل مؤشرات توجيهية للتشخيص وليست وصفات سريرية مطلقة. نسق دائماً رعايتك الطبية مع طبيب سريري معتمد.",
  "Assessment Score:": "درجة التقييم:",
  "Risk level:": "مستوى المخاطر:",
  "AI Recommendation": "توصية الذكاء الاصطناعي",
  "Restart Assessment": "إعادة بدء التقييم",
  "Generate AI Diagnostic Recommendation": "إنشاء توصية التشخيص الذكي",
  "AI Medical Assisting Bot": "مساعد طبي بالذكاء الاصطناعي",
  "Select a body area focus below to refine AI diagnosis": "اختر منطقة التركيز في الجسم بالأسفل لتحسين تشخيص الذكاء الاصطناعي",
  "Ask medical inquiries (e.g. What are symptoms of iron deficiency?)...": "اطرح استفسارات طبية (مثال: ما هي أعراض نقص الحديد؟)...",
  "Hello! I am your AI Medical Assistant. Please describe any symptoms or wellness concerns you have, and I will offer guidance.": "مرحباً بك! أنا مساعدك الطبي بالذكاء الاصطناعي. يرجى وصف أي أعراض أو مخاوف صحية لديك، وسأقدم لك الإرشادات والتشخيص الأولي.",
  "Are you experiencing persistent headaches?": "هل تعاني من صداع مستمر؟",
  "No headaches": "لا يوجد صداع",
  "Mild / Intermittent headaches": "صداع خفيف / متقطع",
  "Constant / Severe headaches": "صداع مستمر / شديد",
  "Do you have difficulty breathing during daily tasks?": "هل تواجه صعوبة في التنفس أثناء المهام اليومية؟",
  "No breathing difficulties": "لا توجد صعوبة في التنفس",
  "Occasional chest tightness": "ضيق عرضي في الصدر",
  "Severe shortness of breath": "ضيق شديد في التنفس",
  "Have you recorded an elevated body temperature?": "هل سجلت ارتفاعاً في درجة حرارة الجسم؟",
  "Normal body temperature (<37°C)": "درجة حرارة طبيعية (<37 درجة مئوية)",
  "Low-grade fever (37°C - 38°C)": "حمى خفيفة (37 - 38 درجة مئوية)",
  "High-grade fever (>38°C)": "حمى شديدة (>38 درجة مئوية)",
  "High": "مرتفع",
  "Medium": "متوسط",
  "Low": "منخفض",
  "Please answer all questions": "يرجى الإجابة على جميع الأسئلة",
  "AI Diagnostic Assessment saved successfully!": "تم حفظ تقييم التشخيص الذكي بنجاح!",
  "Failed to submit assessment": "فشل إرسال التقييم",
  "Emergency Warning: Your symptoms score indicates potential health distress. We recommend scheduling an immediate clinical visit or contacting emergency services.": "تحذير طارئ: درجة الأعراض تشير إلى احتمال وجود وعكة صحية طارئة. ننصحك بزيارة عيادة فوراً أو الاتصال بخدمات الطوارئ.",
  "Clinical Advice: You have mild to moderate symptoms. We suggest booking a virtual consultation with a general practitioner and tracking daily symptoms.": "استشارة سريرية: لديك أعراض خفيفة إلى متوسطة. نقترح عليك حجز استشارة افتراضية مع طبيب عام ومتابعة الأعراض اليومية.",
  "Wellness Advice: Your health indices look stable. Continue to stay hydrated, ensure proper rest, and eat balanced meals.": "نصيحة صحية: مؤشراتك الصحية تبدو مستقرة. استمر في شرب السوائل، خذ قسطاً كافياً من الراحة، وتناول وجبات متوازنة.",
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("lang");
    return (saved === "ar" || saved === "en") ? saved : "en";
  });

  const setLang = (newLang: Language) => {
    localStorage.setItem("lang", newLang);
    setLangState(newLang);
  };

  useEffect(() => {
    const root = window.document.documentElement;
    if (lang === "ar") {
      root.setAttribute("dir", "rtl");
      root.setAttribute("lang", "ar");
    } else {
      root.setAttribute("dir", "ltr");
      root.setAttribute("lang", "en");
    }
  }, [lang]);

  const t = (key: string): string => {
    if (lang === "ar" && arabicTranslations[key]) {
      return arabicTranslations[key];
    }
    return key;
  };

  const isRtl = lang === "ar";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
